// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDU9g0Z9bYJ_5s14MFM0Pqw846a5hZCtg',
    appId: '1:117795933158:web:5a4f497a63fd7c42cb6427',
    messagingSenderId: '117795933158',
    projectId: 'avu-avu-bb80d',
    authDomain: 'avu-avu-bb80d.firebaseapp.com',
    storageBucket: 'avu-avu-bb80d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2S1IgcAe2S2JiAGvZpM0v1GLq3SWuOGM',
    appId: '1:117795933158:android:8abf4c070a2110fecb6427',
    messagingSenderId: '117795933158',
    projectId: 'avu-avu-bb80d',
    storageBucket: 'avu-avu-bb80d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwn8nn1QBMJ3WHbv3puuk7oZBoVUZAJ8o',
    appId: '1:117795933158:ios:05a3e247de4cfebecb6427',
    messagingSenderId: '117795933158',
    projectId: 'avu-avu-bb80d',
    storageBucket: 'avu-avu-bb80d.appspot.com',
    iosBundleId: 'com.example.avu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwn8nn1QBMJ3WHbv3puuk7oZBoVUZAJ8o',
    appId: '1:117795933158:ios:00d91f42614094ebcb6427',
    messagingSenderId: '117795933158',
    projectId: 'avu-avu-bb80d',
    storageBucket: 'avu-avu-bb80d.appspot.com',
    iosBundleId: 'com.example.avu.RunnerTests',
  );
}
